vich_uploader:
    db_driver: orm

    mappings:
       cv:
           uri_prefix: /files/cv
           upload_destination: '%kernel.project_dir%/public/files/cv'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
